"use client";

import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from "react";

export type Language = "en" | "de" | "it" | "fr" | "es";
type Theme = "dark" | "light";
type FormatValues = Record<string, string | number>;
type Preferences = {
  language: Language;
  theme: Theme;
  setLanguage: (language: Language) => void;
  setTheme: (theme: Theme) => void;
  t: (key: string) => string;
  tf: (key: string, values: FormatValues) => string;
};

const dictionary: Record<Language, Record<string, string>> = {
  en: {
    active: "Active",
    activeTesters: "Active testers",
    addTester: "Add tester",
    admin: "Admin",
    adminCooldowns: "Cooldowns",
    adminDiscord: "Discord",
    adminGamemodes: "Gamemodes",
    adminPanel: "Admin Panel",
    adminPlayers: "Players",
    addPlayer: "Add player",
    recordTest: "Record test",
    recordTestHint: "Log a gamemode result for a player - creates the player if they don't exist yet, and updates their rank automatically.",
    testRecorded: "Test recorded.",
    testFailed: "Couldn't record the test - try again.",
    notesOptional: "Notes (optional)",
    submitting: "Submitting...",
    username: "Minecraft username",
    noPlayersYet: "No players yet - add one on the left.",
    adminQueue: "Queue",
    adminRegions: "Regions",
    adminTester: "Tester",
    adminText: "A single panel for players, tiers, queue, waitlist, testers, regions, gamemodes, cooldowns and Discord settings.",
    adminTiers: "Tiers",
    adminTitle: "Admin control center.",
    accessDenied: "Access denied",
    adminAccessDeniedText: "This area is restricted to server staff. Log in with an authorized Discord account to continue.",
    adminWaitlist: "Waitlist",
    allRegions: "All Regions",
    allTiers: "All Tiers",
    api: "API",
    autoSyncedEverywhere: "Auto synced everywhere",
    back: "Back",
    botCommands: "Bot commands",
    by: "by",
    combatSpecialist: "Combat Specialist",
    checkingDiscordLoginToken: "Checking Discord login token...",
    cooldownUntil: "Cooldown active until {time}",
    create: "Create",
    createGamemode: "Create gamemode",
    customTestingMode: "Custom testing mode.",
    dashboard: "Dashboard",
    delete: "Delete",
    deploymentReady: "Deployment Ready",
    deploymentText: "Run `npm install`, copy `.env.example` to `.env`, then use `npm run dev`. Docker support is included for PostgreSQL.",
    deploymentTitle: "Start locally, then connect PostgreSQL and Discord.",
    description: "Description",
    disabled: "disabled",
    disabledLabel: "Disabled",
    discord: "Join Discord",
    discordIdOptional: "Discord ID (optional)",
    discordOauth: "Discord OAuth",
    enabled: "enabled",
    enabledLabel: "Enabled",
    expires: "expires",
    featureAdminText: "Players, tiers, regions, testers, cooldowns, gamemodes and Discord settings are managed from one panel.",
    featureAdminTitle: "Admin Control",
    featureModesText: "Overall, Vanilla, UHC, Pot, NethOP, SMP, Sword, Axe and Mace are wired into ranking, queue and bot commands.",
    featureModesTitle: "Multi Gamemode Ranking",
    featureQueueText: "Queue limits, priority positions, auto promotion and tester notifications are prepared in the API flow.",
    featureQueueTitle: "Queue and Waitlist",
    featureTesterText: "Testers can submit results, add notes and trigger website plus Discord result updates.",
    featureTesterTitle: "Tester Operations",
    fetchingPlayer: "Fetching live player data from the API.",
    footerFor: "{website} for {server}",
    free: "free",
    gamemodeCooldown: "Gamemode cooldown: 72 hours per tested mode",
    gamemodeQueue: "{mode} queue",
    gamemodeTiers: "Gamemode Tiers",
    gamemodes: "Gamemodes",
    getStarted: "Get Started",
    globalCooldown: "Global cooldown: 24 hours after every test",
    history: "History",
    homeBadge: "Minecraft SaaS tier network",
    homeSubtitle: "The complete ranking, testing and queue management solution for Minecraft servers.",
    homeTitle: "Minecraft Tier Testing Platform",
    inactive: "Inactive",
    joinDiscord: "Join Discord",
    joinQueue: "Join Queue",
    jwtReady: "JWT + Discord OAuth ready",
    language: "Language",
    latestTests: "Latest tests",
    leaveQueue: "Leave Queue",
    leftLocalQueue: "{username} left the local queue view.",
    live: "Live",
    liveLeaderboard: "Live leaderboard",
    liveQueue: "Live Queue",
    loadingLoginState: "Loading login state...",
    loadingProfile: "Loading Profile",
    login: "Discord Login",
    logout: "Log out",
    loginStatus: "Login status",
    minPoints: "Min {points} points",
    minecraftUsername: "Minecraft username",
    modulesTitle: "Built for serious testing networks.",
    name: "Name",
    next: "Next",
    noLoginToken: "No login token found. Start Discord OAuth from the header login button.",
    savedLoginToken: "Discord login token saved locally. You can now call protected admin routes with this JWT.",
    noPlayersMatch: "No players match the current filters.",
    noTestsRecorded: "No tests recorded yet.",
    noTestedPlayers: "No tested players yet",
    noWaitlistedPlayers: "No waitlisted players.",
    openFullRanking: "Open full ranking",
    openNameMc: "Open NameMC",
    operations: "Operations",
    optional: "optional",
    oauthRoute: "OAuth route",
    page: "Page",
    player: "Player",
    playerMissing: "No player with this username, UUID or ID was found in the API.",
    playerProfile: "Player Profile",
    players: "Players",
    playersFound: "players found",
    playersWaitingNow: "Players waiting now",
    points: "Points",
    pointsLower: "points",
    position: "Position",
    positionsAndEta: "Positions and ETA",
    prev: "Prev",
    priorityQueue: "Priority queue",
    queue: "Queue",
    queueAddedLocal: "Added locally. Start the API for persistent queue updates.",
    queueInitialStatus: "Queue limit, cooldowns and waitlist promotion are handled by the API.",
    queueJoinChecks: "Queue join checks both scopes before accepting players",
    queueJoinText: "Enter your Minecraft username, choose region and gamemode, then join the queue. Full queues move players to the waitlist automatically.",
    queueMetricDetail: "Players waiting now",
    queueRequestFailed: "Queue request failed",
    queueSnapshot: "Queue Snapshot",
    queueSystem: "Queue System",
    queueText: "Queue positions, estimated wait time, active testers, priority handling and waitlist promotion are part of the same workflow.",
    queueTitle: "Book your next test.",
    rank: "Rank",
    ranking: "Ranking",
    rankingEyebrow: "Ranking System",
    rankingPreview: "Ranking Preview",
    rankingPreviewTitle: "Search, filter and rank every mode.",
    rankingText: "Filter by player, region, gamemode and tier. Equal points share the same placement.",
    rankingTitle: "Complete player leaderboard.",
    region: "Region",
    requestTierTest: "Request a tier test",
    resultEmbedCommand: "Result embed command",
    search: "Search player or UUID",
    serverIp: "Server IP",
    slug: "Slug",
    statusLabel: "Status: {status}",
    storedTierTestResults: "Stored tier test results",
    systemModules: "System Modules",
    tester: "Tester",
    testerName: "Tester name",
    testerWorkflowText: "Slash commands, cooldown checks, result notes and Discord embeds are aligned with the same backend state used by the website.",
    testerWorkflowTitle: "Tester-ready workflow.",
    testedPlayers: "tested players",
    tests: "Tests",
    themeToggle: "Toggle theme",
    tier: "Tier",
    tierBoard: "Tier board",
    tierNetwork: "Tier testing network",
    tiers: "Tiers",
    topRanked: "Top Ranked",
    verifiedMinecraftProfiles: "Verified Minecraft profiles",
    waitlist: "Waitlist"
  },
  de: {
    active: "Aktiv",
    activeTesters: "Aktive Tester",
    addTester: "Tester hinzufuegen",
    admin: "Admin",
    adminCooldowns: "Cooldowns",
    adminDiscord: "Discord",
    adminGamemodes: "Gamemodes",
    adminPanel: "Admin Panel",
    adminPlayers: "Spieler",
    addPlayer: "Spieler hinzufuegen",
    recordTest: "Test erfassen",
    recordTestHint: "Erfasse ein Gamemode-Ergebnis fuer einen Spieler - legt den Spieler an, falls er noch nicht existiert, und aktualisiert automatisch seinen Rang.",
    testRecorded: "Test erfasst.",
    testFailed: "Test konnte nicht erfasst werden - bitte erneut versuchen.",
    notesOptional: "Notizen (optional)",
    submitting: "Wird gesendet...",
    username: "Minecraft-Benutzername",
    noPlayersYet: "Noch keine Spieler - links einen hinzufuegen.",
    adminQueue: "Warteschlange",
    adminRegions: "Regionen",
    adminTester: "Tester",
    adminText: "Ein zentrales Panel fuer Spieler, Tiers, Warteschlange, Waitlist, Tester, Regionen, Gamemodes, Cooldowns und Discord-Einstellungen.",
    adminTiers: "Tiers",
    adminTitle: "Admin Kontrollzentrum.",
    accessDenied: "Zugriff verweigert",
    adminAccessDeniedText: "Dieser Bereich ist nur fuer Server-Mitarbeiter zugaenglich. Melde dich mit einem autorisierten Discord-Konto an, um fortzufahren.",
    adminWaitlist: "Waitlist",
    allRegions: "Alle Regionen",
    allTiers: "Alle Tiers",
    api: "API",
    autoSyncedEverywhere: "Ueberall automatisch synchron",
    back: "Zurueck",
    botCommands: "Bot-Befehle",
    by: "von",
    combatSpecialist: "Combat Spezialist",
    checkingDiscordLoginToken: "Discord Login-Token wird geprueft...",
    cooldownUntil: "Cooldown aktiv bis {time}",
    create: "Erstellen",
    createGamemode: "Gamemode erstellen",
    customTestingMode: "Eigener Testing-Modus.",
    dashboard: "Dashboard",
    delete: "Loeschen",
    deploymentReady: "Deployment bereit",
    deploymentText: "Fuehre `npm install` aus, kopiere `.env.example` zu `.env` und starte dann mit `npm run dev`. Docker-Support fuer PostgreSQL ist enthalten.",
    deploymentTitle: "Lokal starten, danach PostgreSQL und Discord verbinden.",
    description: "Beschreibung",
    disabled: "deaktiviert",
    disabledLabel: "Deaktiviert",
    discord: "Discord beitreten",
    discordIdOptional: "Discord ID (optional)",
    discordOauth: "Discord OAuth",
    enabled: "aktiviert",
    enabledLabel: "Aktiviert",
    expires: "laeuft ab",
    featureAdminText: "Spieler, Tiers, Regionen, Tester, Cooldowns, Gamemodes und Discord-Einstellungen werden in einem Panel verwaltet.",
    featureAdminTitle: "Admin Kontrolle",
    featureModesText: "Overall, Vanilla, UHC, Pot, NethOP, SMP, Sword, Axe und Mace sind mit Ranking, Queue und Bot-Befehlen verbunden.",
    featureModesTitle: "Multi-Gamemode Ranking",
    featureQueueText: "Queue-Limits, Prioritaetsplaetze, automatische Promotion und Tester-Benachrichtigungen sind im API-Flow vorbereitet.",
    featureQueueTitle: "Queue und Waitlist",
    featureTesterText: "Tester koennen Ergebnisse eintragen, Notizen hinzufuegen und Website- sowie Discord-Resultate ausloesen.",
    featureTesterTitle: "Tester Betrieb",
    fetchingPlayer: "Live-Spielerdaten werden aus der API geladen.",
    footerFor: "{website} fuer {server}",
    free: "frei",
    gamemodeCooldown: "Gamemode-Cooldown: 72 Stunden pro getestetem Modus",
    gamemodeQueue: "{mode} Queue",
    gamemodeTiers: "Gamemode Tiers",
    gamemodes: "Gamemodes",
    getStarted: "Loslegen",
    globalCooldown: "Globaler Cooldown: 24 Stunden nach jedem Test",
    history: "Historie",
    homeBadge: "Minecraft SaaS Tier-Netzwerk",
    homeSubtitle: "Die komplette Ranking-, Testing- und Queue-Management-Loesung fuer Minecraft-Server.",
    homeTitle: "Minecraft Tier Testing Plattform",
    inactive: "Inaktiv",
    joinDiscord: "Discord beitreten",
    joinQueue: "Queue beitreten",
    jwtReady: "JWT + Discord OAuth bereit",
    language: "Sprache",
    latestTests: "Neueste Tests",
    leaveQueue: "Queue verlassen",
    leftLocalQueue: "{username} hat die lokale Queue-Ansicht verlassen.",
    live: "Live",
    liveLeaderboard: "Live-Rangliste",
    liveQueue: "Live Queue",
    loadingLoginState: "Login-Status wird geladen...",
    loadingProfile: "Profil wird geladen",
    login: "Discord Login",
    logout: "Abmelden",
    loginStatus: "Login-Status",
    minPoints: "Min {points} Punkte",
    minecraftUsername: "Minecraft Benutzername",
    modulesTitle: "Gebaut fuer ernsthafte Testing-Netzwerke.",
    name: "Name",
    next: "Weiter",
    noLoginToken: "Kein Login-Token gefunden. Starte Discord OAuth ueber den Login-Button im Header.",
    savedLoginToken: "Discord Login-Token wurde lokal gespeichert. Geschuetzte Admin-Routen koennen jetzt mit diesem JWT aufgerufen werden.",
    noPlayersMatch: "Keine Spieler passen zu den aktuellen Filtern.",
    noTestsRecorded: "Noch keine Tests erfasst.",
    noTestedPlayers: "Noch keine getesteten Spieler",
    noWaitlistedPlayers: "Keine Spieler auf der Waitlist.",
    openFullRanking: "Volles Ranking oeffnen",
    openNameMc: "NameMC oeffnen",
    operations: "Betrieb",
    optional: "optional",
    oauthRoute: "OAuth Route",
    page: "Seite",
    player: "Spieler",
    playerMissing: "Kein Spieler mit diesem Namen, dieser UUID oder ID wurde in der API gefunden.",
    playerProfile: "Spielerprofil",
    players: "Spieler",
    playersFound: "Spieler gefunden",
    playersWaitingNow: "Spieler warten aktuell",
    points: "Punkte",
    pointsLower: "Punkte",
    position: "Position",
    positionsAndEta: "Positionen und ETA",
    prev: "Zurueck",
    priorityQueue: "Priority Queue",
    queue: "Warteschlange",
    queueAddedLocal: "Lokal hinzugefuegt. Starte die API fuer persistente Queue-Updates.",
    queueInitialStatus: "Queue-Limit, Cooldowns und Waitlist-Promotion werden von der API behandelt.",
    queueJoinChecks: "Queue-Beitritt prueft beide Cooldown-Bereiche vor dem Annehmen von Spielern",
    queueJoinText: "Gib deinen Minecraft-Benutzernamen ein, waehle Region und Gamemode und tritt der Queue bei. Volle Queues verschieben Spieler automatisch in die Waitlist.",
    queueMetricDetail: "Spieler warten aktuell",
    queueRequestFailed: "Queue-Anfrage fehlgeschlagen",
    queueSnapshot: "Queue Snapshot",
    queueSystem: "Queue System",
    queueText: "Queue-Positionen, geschaetzte Wartezeit, aktive Tester, Prioritaeten und Waitlist-Promotion sind Teil desselben Workflows.",
    queueTitle: "Buche deinen naechsten Test.",
    rank: "Rang",
    ranking: "Ranking",
    rankingEyebrow: "Ranking System",
    rankingPreview: "Ranking Vorschau",
    rankingPreviewTitle: "Suche, filtere und ranke jeden Modus.",
    rankingText: "Filtere nach Spieler, Region, Gamemode und Tier. Bei gleichen Punkten teilen sich Spieler denselben Rang.",
    rankingTitle: "Komplette Spieler-Rangliste.",
    region: "Region",
    requestTierTest: "Tier-Test anfragen",
    resultEmbedCommand: "Result-Embed-Befehl",
    search: "Spieler oder UUID suchen",
    serverIp: "Server IP",
    slug: "Slug",
    statusLabel: "Status: {status}",
    storedTierTestResults: "Gespeicherte Tier-Test-Ergebnisse",
    systemModules: "Systemmodule",
    tester: "Tester",
    testerName: "Tester Name",
    testerWorkflowText: "Slash-Commands, Cooldown-Pruefungen, Result-Notizen und Discord-Embeds nutzen denselben Backend-Status wie die Website.",
    testerWorkflowTitle: "Workflow bereit fuer Tester.",
    testedPlayers: "getestete Spieler",
    tests: "Tests",
    themeToggle: "Theme umschalten",
    tier: "Tier",
    tierBoard: "Tier Board",
    tierNetwork: "Tier-Testing Netzwerk",
    tiers: "Tiers",
    topRanked: "Top Ranking",
    verifiedMinecraftProfiles: "Verifizierte Minecraft-Profile",
    waitlist: "Waitlist"
  },
  it: {
    active: "Attivo",
    activeTesters: "Tester attivi",
    addTester: "Aggiungi tester",
    admin: "Admin",
    adminCooldowns: "Cooldown",
    adminDiscord: "Discord",
    adminGamemodes: "Modalita",
    adminPanel: "Pannello admin",
    adminPlayers: "Giocatori",
    addPlayer: "Aggiungi giocatore",
    recordTest: "Registra test",
    recordTestHint: "Registra un risultato di gamemode per un giocatore - crea il giocatore se non esiste ancora e aggiorna automaticamente il suo rank.",
    testRecorded: "Test registrato.",
    testFailed: "Impossibile registrare il test - riprova.",
    notesOptional: "Note (opzionale)",
    submitting: "Invio in corso...",
    username: "Nome utente Minecraft",
    noPlayersYet: "Ancora nessun giocatore - aggiungine uno a sinistra.",
    adminQueue: "Coda",
    adminRegions: "Regioni",
    adminTester: "Tester",
    adminText: "Un unico pannello per giocatori, tier, coda, waitlist, tester, regioni, modalita, cooldown e impostazioni Discord.",
    adminTiers: "Tier",
    adminTitle: "Centro di controllo admin.",
    accessDenied: "Accesso negato",
    adminAccessDeniedText: "Questa area e riservata allo staff del server. Accedi con un account Discord autorizzato per continuare.",
    adminWaitlist: "Waitlist",
    allRegions: "Tutte le regioni",
    allTiers: "Tutti i tier",
    api: "API",
    autoSyncedEverywhere: "Sincronizzato ovunque",
    back: "Indietro",
    botCommands: "Comandi bot",
    by: "da",
    combatSpecialist: "Specialista combat",
    checkingDiscordLoginToken: "Controllo token login Discord...",
    cooldownUntil: "Cooldown attivo fino a {time}",
    create: "Crea",
    createGamemode: "Crea modalita",
    customTestingMode: "Modalita di test personalizzata.",
    dashboard: "Dashboard",
    delete: "Elimina",
    deploymentReady: "Pronto per il deploy",
    deploymentText: "Esegui `npm install`, copia `.env.example` in `.env`, poi usa `npm run dev`. Il supporto Docker per PostgreSQL e incluso.",
    deploymentTitle: "Avvia in locale, poi collega PostgreSQL e Discord.",
    description: "Descrizione",
    disabled: "disattivato",
    disabledLabel: "Disattivato",
    discord: "Entra Discord",
    discordIdOptional: "Discord ID (opzionale)",
    discordOauth: "Discord OAuth",
    enabled: "attivato",
    enabledLabel: "Attivato",
    expires: "scade",
    featureAdminText: "Giocatori, tier, regioni, tester, cooldown, modalita e impostazioni Discord sono gestiti da un solo pannello.",
    featureAdminTitle: "Controllo admin",
    featureModesText: "Overall, Vanilla, UHC, Pot, NethOP, SMP, Sword, Axe e Mace sono collegati a ranking, coda e comandi bot.",
    featureModesTitle: "Ranking multi-modalita",
    featureQueueText: "Limiti coda, posizioni prioritarie, promozione automatica e notifiche tester sono preparati nel flusso API.",
    featureQueueTitle: "Coda e waitlist",
    featureTesterText: "I tester possono inviare risultati, aggiungere note e aggiornare sito e Discord.",
    featureTesterTitle: "Operazioni tester",
    fetchingPlayer: "Caricamento dati live del giocatore dall'API.",
    footerFor: "{website} per {server}",
    free: "libero",
    gamemodeCooldown: "Cooldown modalita: 72 ore per modalita testata",
    gamemodeQueue: "Coda {mode}",
    gamemodeTiers: "Tier modalita",
    gamemodes: "Modalita",
    getStarted: "Inizia",
    globalCooldown: "Cooldown globale: 24 ore dopo ogni test",
    history: "Cronologia",
    homeBadge: "Rete tier Minecraft SaaS",
    homeSubtitle: "La soluzione completa per ranking, test e gestione code dei server Minecraft.",
    homeTitle: "Piattaforma Minecraft Tier Testing",
    inactive: "Inattivo",
    joinDiscord: "Entra Discord",
    joinQueue: "Entra in coda",
    jwtReady: "JWT + Discord OAuth pronto",
    language: "Lingua",
    latestTests: "Ultimi test",
    leaveQueue: "Lascia coda",
    leftLocalQueue: "{username} ha lasciato la vista locale della coda.",
    live: "Live",
    liveLeaderboard: "Classifica live",
    liveQueue: "Coda live",
    loadingLoginState: "Caricamento stato login...",
    loadingProfile: "Caricamento profilo",
    login: "Login Discord",
    logout: "Esci",
    loginStatus: "Stato login",
    minPoints: "Min {points} punti",
    minecraftUsername: "Username Minecraft",
    modulesTitle: "Creato per reti di testing serie.",
    name: "Nome",
    next: "Succ",
    noLoginToken: "Nessun token login trovato. Avvia Discord OAuth dal pulsante login nell'header.",
    savedLoginToken: "Token login Discord salvato localmente. Ora puoi chiamare route admin protette con questo JWT.",
    noPlayersMatch: "Nessun giocatore corrisponde ai filtri attuali.",
    noTestsRecorded: "Nessun test registrato.",
    noTestedPlayers: "Nessun giocatore testato",
    noWaitlistedPlayers: "Nessun giocatore in waitlist.",
    openFullRanking: "Apri ranking completo",
    openNameMc: "Apri NameMC",
    operations: "Operazioni",
    optional: "opzionale",
    oauthRoute: "Route OAuth",
    page: "Pagina",
    player: "Giocatore",
    playerMissing: "Nessun giocatore con questo username, UUID o ID e stato trovato nell'API.",
    playerProfile: "Profilo giocatore",
    players: "Giocatori",
    playersFound: "giocatori trovati",
    playersWaitingNow: "Giocatori in attesa",
    points: "Punti",
    pointsLower: "punti",
    position: "Posizione",
    positionsAndEta: "Posizioni e ETA",
    prev: "Prec",
    priorityQueue: "Coda prioritaria",
    queue: "Coda",
    queueAddedLocal: "Aggiunto localmente. Avvia l'API per aggiornamenti persistenti della coda.",
    queueInitialStatus: "Limite coda, cooldown e promozione waitlist sono gestiti dall'API.",
    queueJoinChecks: "L'ingresso in coda controlla entrambi gli ambiti prima di accettare giocatori",
    queueJoinText: "Inserisci il tuo username Minecraft, scegli regione e modalita, poi entra in coda. Le code piene spostano automaticamente i giocatori nella waitlist.",
    queueMetricDetail: "Giocatori in attesa",
    queueRequestFailed: "Richiesta coda fallita",
    queueSnapshot: "Snapshot coda",
    queueSystem: "Sistema coda",
    queueText: "Posizioni, tempo stimato, tester attivi, priorita e promozione waitlist fanno parte dello stesso workflow.",
    queueTitle: "Prenota il tuo prossimo test.",
    rank: "Rank",
    ranking: "Classifica",
    rankingEyebrow: "Sistema ranking",
    rankingPreview: "Anteprima ranking",
    rankingPreviewTitle: "Cerca, filtra e classifica ogni modalita.",
    rankingText: "Filtra per giocatore, regione, modalita e tier. I punti uguali condividono la stessa posizione.",
    rankingTitle: "Classifica giocatori completa.",
    region: "Regione",
    requestTierTest: "Richiedi un tier test",
    resultEmbedCommand: "Comando embed risultato",
    search: "Cerca giocatore o UUID",
    serverIp: "IP server",
    slug: "Slug",
    statusLabel: "Stato: {status}",
    storedTierTestResults: "Risultati tier test salvati",
    systemModules: "Moduli sistema",
    tester: "Tester",
    testerName: "Nome tester",
    testerWorkflowText: "Slash command, controlli cooldown, note risultato ed embed Discord usano lo stesso stato backend del sito.",
    testerWorkflowTitle: "Workflow pronto per tester.",
    testedPlayers: "giocatori testati",
    tests: "Test",
    themeToggle: "Cambia tema",
    tier: "Tier",
    tierBoard: "Tier board",
    tierNetwork: "Rete tier testing",
    tiers: "Tier",
    topRanked: "Top ranking",
    verifiedMinecraftProfiles: "Profili Minecraft verificati",
    waitlist: "Waitlist"
  },
  fr: {
    active: "Actif",
    activeTesters: "Testeurs actifs",
    addTester: "Ajouter testeur",
    admin: "Admin",
    adminCooldowns: "Cooldowns",
    adminDiscord: "Discord",
    adminGamemodes: "Modes",
    adminPanel: "Panneau admin",
    adminPlayers: "Joueurs",
    addPlayer: "Ajouter un joueur",
    recordTest: "Enregistrer un test",
    recordTestHint: "Enregistre un resultat de gamemode pour un joueur - le cree s'il n'existe pas encore, et met a jour son rang automatiquement.",
    testRecorded: "Test enregistre.",
    testFailed: "Impossible d'enregistrer le test - reessayez.",
    notesOptional: "Notes (optionnel)",
    submitting: "Envoi en cours...",
    username: "Nom d'utilisateur Minecraft",
    noPlayersYet: "Aucun joueur pour l'instant - ajoutez-en un a gauche.",
    adminQueue: "File",
    adminRegions: "Regions",
    adminTester: "Testeur",
    adminText: "Un seul panneau pour joueurs, tiers, file, waitlist, testeurs, regions, modes, cooldowns et parametres Discord.",
    adminTiers: "Tiers",
    adminTitle: "Centre de controle admin.",
    accessDenied: "Acces refuse",
    adminAccessDeniedText: "Cette zone est reservee au personnel du serveur. Connectez-vous avec un compte Discord autorise pour continuer.",
    adminWaitlist: "Waitlist",
    allRegions: "Toutes les regions",
    allTiers: "Tous les tiers",
    api: "API",
    autoSyncedEverywhere: "Synchronise partout",
    back: "Retour",
    botCommands: "Commandes bot",
    by: "par",
    combatSpecialist: "Specialiste combat",
    checkingDiscordLoginToken: "Verification du token login Discord...",
    cooldownUntil: "Cooldown actif jusqu'a {time}",
    create: "Creer",
    createGamemode: "Creer mode",
    customTestingMode: "Mode de test personnalise.",
    dashboard: "Dashboard",
    delete: "Supprimer",
    deploymentReady: "Pret au deploy",
    deploymentText: "Lance `npm install`, copie `.env.example` vers `.env`, puis utilise `npm run dev`. Le support Docker pour PostgreSQL est inclus.",
    deploymentTitle: "Demarre en local, puis connecte PostgreSQL et Discord.",
    description: "Description",
    disabled: "desactive",
    disabledLabel: "Desactive",
    discord: "Rejoindre Discord",
    discordIdOptional: "Discord ID (optionnel)",
    discordOauth: "Discord OAuth",
    enabled: "active",
    enabledLabel: "Active",
    expires: "expire",
    featureAdminText: "Joueurs, tiers, regions, testeurs, cooldowns, modes et parametres Discord sont geres depuis un panneau.",
    featureAdminTitle: "Controle admin",
    featureModesText: "Overall, Vanilla, UHC, Pot, NethOP, SMP, Sword, Axe et Mace sont connectes au ranking, a la file et aux commandes bot.",
    featureModesTitle: "Ranking multi-mode",
    featureQueueText: "Limites de file, priorites, promotion auto et notifications testeurs sont preparees dans le flux API.",
    featureQueueTitle: "File et waitlist",
    featureTesterText: "Les testeurs peuvent envoyer des resultats, ajouter des notes et declencher les mises a jour site et Discord.",
    featureTesterTitle: "Operations testeurs",
    fetchingPlayer: "Chargement des donnees joueur live depuis l'API.",
    footerFor: "{website} pour {server}",
    free: "libre",
    gamemodeCooldown: "Cooldown mode: 72 heures par mode teste",
    gamemodeQueue: "File {mode}",
    gamemodeTiers: "Tiers des modes",
    gamemodes: "Modes",
    getStarted: "Commencer",
    globalCooldown: "Cooldown global: 24 heures apres chaque test",
    history: "Historique",
    homeBadge: "Reseau tier Minecraft SaaS",
    homeSubtitle: "La solution complete de ranking, test et gestion de file pour serveurs Minecraft.",
    homeTitle: "Plateforme Minecraft Tier Testing",
    inactive: "Inactif",
    joinDiscord: "Rejoindre Discord",
    joinQueue: "Rejoindre file",
    jwtReady: "JWT + Discord OAuth pret",
    language: "Langue",
    latestTests: "Derniers tests",
    leaveQueue: "Quitter file",
    leftLocalQueue: "{username} a quitte la vue locale de la file.",
    live: "Live",
    liveLeaderboard: "Classement live",
    liveQueue: "File live",
    loadingLoginState: "Chargement du statut login...",
    loadingProfile: "Chargement profil",
    login: "Login Discord",
    logout: "Se deconnecter",
    loginStatus: "Statut login",
    minPoints: "Min {points} points",
    minecraftUsername: "Pseudo Minecraft",
    modulesTitle: "Concu pour des reseaux de test serieux.",
    name: "Nom",
    next: "Suiv",
    noLoginToken: "Aucun token login trouve. Lance Discord OAuth depuis le bouton login dans le header.",
    savedLoginToken: "Token login Discord enregistre localement. Tu peux maintenant appeler les routes admin protegees avec ce JWT.",
    noPlayersMatch: "Aucun joueur ne correspond aux filtres actuels.",
    noTestsRecorded: "Aucun test enregistre.",
    noTestedPlayers: "Aucun joueur teste",
    noWaitlistedPlayers: "Aucun joueur en waitlist.",
    openFullRanking: "Ouvrir ranking complet",
    openNameMc: "Ouvrir NameMC",
    operations: "Operations",
    optional: "optionnel",
    oauthRoute: "Route OAuth",
    page: "Page",
    player: "Joueur",
    playerMissing: "Aucun joueur avec ce pseudo, UUID ou ID n'a ete trouve dans l'API.",
    playerProfile: "Profil joueur",
    players: "Joueurs",
    playersFound: "joueurs trouves",
    playersWaitingNow: "Joueurs en attente",
    points: "Points",
    pointsLower: "points",
    position: "Position",
    positionsAndEta: "Positions et ETA",
    prev: "Prec",
    priorityQueue: "File prioritaire",
    queue: "File",
    queueAddedLocal: "Ajoute localement. Demarre l'API pour des mises a jour persistantes de file.",
    queueInitialStatus: "Limite de file, cooldowns et promotion waitlist sont geres par l'API.",
    queueJoinChecks: "L'entree en file verifie les deux scopes avant d'accepter les joueurs",
    queueJoinText: "Entre ton pseudo Minecraft, choisis region et mode, puis rejoins la file. Les files pleines deplacent automatiquement les joueurs vers la waitlist.",
    queueMetricDetail: "Joueurs en attente",
    queueRequestFailed: "Requete de file echouee",
    queueSnapshot: "Snapshot file",
    queueSystem: "Systeme de file",
    queueText: "Positions de file, attente estimee, testeurs actifs, priorites et promotion waitlist font partie du meme workflow.",
    queueTitle: "Reserve ton prochain test.",
    rank: "Rang",
    ranking: "Classement",
    rankingEyebrow: "Systeme ranking",
    rankingPreview: "Apercu ranking",
    rankingPreviewTitle: "Cherche, filtre et classe chaque mode.",
    rankingText: "Filtre par joueur, region, mode et tier. Les points egaux partagent la meme place.",
    rankingTitle: "Classement complet des joueurs.",
    region: "Region",
    requestTierTest: "Demander un tier test",
    resultEmbedCommand: "Commande embed resultat",
    search: "Chercher joueur ou UUID",
    serverIp: "IP serveur",
    slug: "Slug",
    statusLabel: "Statut: {status}",
    storedTierTestResults: "Resultats de tier test stockes",
    systemModules: "Modules systeme",
    tester: "Testeur",
    testerName: "Nom testeur",
    testerWorkflowText: "Slash commands, controles cooldown, notes de resultat et embeds Discord utilisent le meme etat backend que le site.",
    testerWorkflowTitle: "Workflow pret pour testeurs.",
    testedPlayers: "joueurs testes",
    tests: "Tests",
    themeToggle: "Changer theme",
    tier: "Tier",
    tierBoard: "Tier board",
    tierNetwork: "Reseau tier testing",
    tiers: "Tiers",
    topRanked: "Top classement",
    verifiedMinecraftProfiles: "Profils Minecraft verifies",
    waitlist: "Waitlist"
  },
  es: {
    active: "Activo",
    activeTesters: "Testers activos",
    addTester: "Agregar tester",
    admin: "Admin",
    adminCooldowns: "Cooldowns",
    adminDiscord: "Discord",
    adminGamemodes: "Modos",
    adminPanel: "Panel admin",
    adminPlayers: "Jugadores",
    addPlayer: "Anadir jugador",
    recordTest: "Registrar test",
    recordTestHint: "Registra un resultado de gamemode para un jugador - lo crea si aun no existe y actualiza su rango automaticamente.",
    testRecorded: "Test registrado.",
    testFailed: "No se pudo registrar el test - intentalo de nuevo.",
    notesOptional: "Notas (opcional)",
    submitting: "Enviando...",
    username: "Nombre de usuario de Minecraft",
    noPlayersYet: "Aun no hay jugadores - anade uno a la izquierda.",
    adminQueue: "Cola",
    adminRegions: "Regiones",
    adminTester: "Tester",
    adminText: "Un solo panel para jugadores, tiers, cola, waitlist, testers, regiones, modos, cooldowns y ajustes de Discord.",
    adminTiers: "Tiers",
    adminTitle: "Centro de control admin.",
    accessDenied: "Acceso denegado",
    adminAccessDeniedText: "Esta area esta restringida al personal del servidor. Inicia sesion con una cuenta de Discord autorizada para continuar.",
    adminWaitlist: "Waitlist",
    allRegions: "Todas las regiones",
    allTiers: "Todos los tiers",
    api: "API",
    autoSyncedEverywhere: "Sincronizado en todos lados",
    back: "Volver",
    botCommands: "Comandos bot",
    by: "por",
    combatSpecialist: "Especialista combat",
    checkingDiscordLoginToken: "Verificando token de login Discord...",
    cooldownUntil: "Cooldown activo hasta {time}",
    create: "Crear",
    createGamemode: "Crear modo",
    customTestingMode: "Modo de testing personalizado.",
    dashboard: "Dashboard",
    delete: "Eliminar",
    deploymentReady: "Listo para deploy",
    deploymentText: "Ejecuta `npm install`, copia `.env.example` a `.env` y usa `npm run dev`. Incluye soporte Docker para PostgreSQL.",
    deploymentTitle: "Inicia localmente, luego conecta PostgreSQL y Discord.",
    description: "Descripcion",
    disabled: "desactivado",
    disabledLabel: "Desactivado",
    discord: "Unirse Discord",
    discordIdOptional: "Discord ID (opcional)",
    discordOauth: "Discord OAuth",
    enabled: "activado",
    enabledLabel: "Activado",
    expires: "expira",
    featureAdminText: "Jugadores, tiers, regiones, testers, cooldowns, modos y ajustes Discord se gestionan desde un panel.",
    featureAdminTitle: "Control admin",
    featureModesText: "Overall, Vanilla, UHC, Pot, NethOP, SMP, Sword, Axe y Mace estan conectados a ranking, cola y comandos bot.",
    featureModesTitle: "Ranking multi-modo",
    featureQueueText: "Limites de cola, posiciones prioritarias, promocion automatica y notificaciones a testers estan preparadas en el flujo API.",
    featureQueueTitle: "Cola y waitlist",
    featureTesterText: "Los testers pueden enviar resultados, agregar notas y disparar actualizaciones de web y Discord.",
    featureTesterTitle: "Operaciones tester",
    fetchingPlayer: "Cargando datos live del jugador desde la API.",
    footerFor: "{website} para {server}",
    free: "libre",
    gamemodeCooldown: "Cooldown de modo: 72 horas por modo testeado",
    gamemodeQueue: "Cola {mode}",
    gamemodeTiers: "Tiers de modos",
    gamemodes: "Modos",
    getStarted: "Empezar",
    globalCooldown: "Cooldown global: 24 horas despues de cada test",
    history: "Historial",
    homeBadge: "Red tier Minecraft SaaS",
    homeSubtitle: "La solucion completa de ranking, testing y gestion de cola para servidores Minecraft.",
    homeTitle: "Plataforma Minecraft Tier Testing",
    inactive: "Inactivo",
    joinDiscord: "Unirse Discord",
    joinQueue: "Entrar en cola",
    jwtReady: "JWT + Discord OAuth listo",
    language: "Idioma",
    latestTests: "Ultimos tests",
    leaveQueue: "Salir de cola",
    leftLocalQueue: "{username} salio de la vista local de cola.",
    live: "Live",
    liveLeaderboard: "Leaderboard live",
    liveQueue: "Cola live",
    loadingLoginState: "Cargando estado de login...",
    loadingProfile: "Cargando perfil",
    login: "Login Discord",
    logout: "Cerrar sesion",
    loginStatus: "Estado de login",
    minPoints: "Min {points} puntos",
    minecraftUsername: "Usuario Minecraft",
    modulesTitle: "Construido para redes de testing serias.",
    name: "Nombre",
    next: "Sig",
    noLoginToken: "No se encontro token de login. Inicia Discord OAuth desde el boton login del header.",
    savedLoginToken: "Token de login Discord guardado localmente. Ahora puedes llamar rutas admin protegidas con este JWT.",
    noPlayersMatch: "Ningun jugador coincide con los filtros actuales.",
    noTestsRecorded: "No hay tests registrados.",
    noTestedPlayers: "Ningun jugador testeado",
    noWaitlistedPlayers: "No hay jugadores en waitlist.",
    openFullRanking: "Abrir ranking completo",
    openNameMc: "Abrir NameMC",
    operations: "Operaciones",
    optional: "opcional",
    oauthRoute: "Ruta OAuth",
    page: "Pagina",
    player: "Jugador",
    playerMissing: "No se encontro ningun jugador con este usuario, UUID o ID en la API.",
    playerProfile: "Perfil jugador",
    players: "Jugadores",
    playersFound: "jugadores encontrados",
    playersWaitingNow: "Jugadores esperando",
    points: "Puntos",
    pointsLower: "puntos",
    position: "Posicion",
    positionsAndEta: "Posiciones y ETA",
    prev: "Ant",
    priorityQueue: "Cola prioritaria",
    queue: "Cola",
    queueAddedLocal: "Agregado localmente. Inicia la API para actualizaciones persistentes de cola.",
    queueInitialStatus: "Limite de cola, cooldowns y promocion waitlist son manejados por la API.",
    queueJoinChecks: "La entrada a cola verifica ambos scopes antes de aceptar jugadores",
    queueJoinText: "Ingresa tu usuario Minecraft, elige region y modo, luego entra en cola. Las colas llenas mueven jugadores automaticamente a la waitlist.",
    queueMetricDetail: "Jugadores esperando",
    queueRequestFailed: "Solicitud de cola fallida",
    queueSnapshot: "Snapshot de cola",
    queueSystem: "Sistema de cola",
    queueText: "Posiciones de cola, espera estimada, testers activos, prioridad y promocion waitlist son parte del mismo workflow.",
    queueTitle: "Reserva tu proximo test.",
    rank: "Rango",
    ranking: "Ranking",
    rankingEyebrow: "Sistema ranking",
    rankingPreview: "Vista previa ranking",
    rankingPreviewTitle: "Busca, filtra y rankea cada modo.",
    rankingText: "Filtra por jugador, region, modo y tier. Puntos iguales comparten la misma posicion.",
    rankingTitle: "Leaderboard completo de jugadores.",
    region: "Region",
    requestTierTest: "Solicitar tier test",
    resultEmbedCommand: "Comando embed resultado",
    search: "Buscar jugador o UUID",
    serverIp: "IP servidor",
    slug: "Slug",
    statusLabel: "Estado: {status}",
    storedTierTestResults: "Resultados tier test guardados",
    systemModules: "Modulos del sistema",
    tester: "Tester",
    testerName: "Nombre tester",
    testerWorkflowText: "Slash commands, controles de cooldown, notas de resultado y embeds Discord usan el mismo estado backend del sitio.",
    testerWorkflowTitle: "Workflow listo para testers.",
    testedPlayers: "jugadores testeados",
    tests: "Tests",
    themeToggle: "Cambiar tema",
    tier: "Tier",
    tierBoard: "Tier board",
    tierNetwork: "Red tier testing",
    tiers: "Tiers",
    topRanked: "Top ranking",
    verifiedMinecraftProfiles: "Perfiles Minecraft verificados",
    waitlist: "Waitlist"
  }
};

const PreferencesContext = createContext<Preferences | null>(null);

function format(template: string, values: FormatValues) {
  return template.replace(/\{(\w+)\}/g, (_, key: string) => String(values[key] ?? `{${key}}`));
}

export function PreferencesProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>("en");
  const [theme, setThemeState] = useState<Theme>("dark");

  useEffect(() => {
    const storedLanguage = window.localStorage.getItem("language");
    const storedTheme = window.localStorage.getItem("theme");
    if (storedLanguage === "de" || storedLanguage === "en" || storedLanguage === "it" || storedLanguage === "fr" || storedLanguage === "es") setLanguageState(storedLanguage);
    if (storedTheme === "dark" || storedTheme === "light") setThemeState(storedTheme);
  }, []);

  useEffect(() => {
    document.documentElement.lang = language;
    document.documentElement.dataset.theme = theme;
    document.documentElement.classList.toggle("light", theme === "light");
    document.documentElement.classList.toggle("dark", theme === "dark");
    window.localStorage.setItem("language", language);
    window.localStorage.setItem("theme", theme);
  }, [language, theme]);

  const value = useMemo<Preferences>(() => {
    const translate = (key: string) => dictionary[language][key] || dictionary.en[key] || key;
    return {
      language,
      theme,
      setLanguage: setLanguageState,
      setTheme: setThemeState,
      t: translate,
      tf: (key, values) => format(translate(key), values)
    };
  }, [language, theme]);

  return <PreferencesContext.Provider value={value}>{children}</PreferencesContext.Provider>;
}

export function usePreferences() {
  const context = useContext(PreferencesContext);
  if (!context) throw new Error("usePreferences must be used inside PreferencesProvider");
  return context;
}
